name: 'Pharo 11 CI'

env: 
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest ]
        smalltalk: [ Pharo64-11 ]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.smalltalk }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - name: Load in New Image and Run Tests
        run: smalltalkci -s ${{ matrix.smalltalk }} ${{ matrix.ston }}
        shell: bash
        timeout-minutes: 30
